export const listOfRestaurant = [
  {
    data: {
      id: "255655",
      name: "Cake & Cream",
      cloudinaryImageId: "ac57cc371e73f96f812613f58457aca3",
      areaName: "Jairaj Nagar",
      costForTwo: "₹200 for two",
      cuisines: ["Bakery", "Hot-dog", "pastery", "Cake", "Thick- shake"],
      avgRating: 4.3,
      veg: true,
      parentId: "54670",
      avgRatingString: "4",
      totalRatingsString: "20+",
    },
  },
  {
    data: {
      id: "350363",
      name: "Haldiram's Sweets and Namkeen",
      cloudinaryImageId: "25c3a7d394d6c5556b134385f7d665b0",
      avgRating: 4.6,
      veg: true,
      cuisines: ["North Indian", "South Indian", "Chinese", "Pizzas"],
      parentId: "391465",
      avgRatingString: "4.6",
      totalRatingsString: "100+",
    },
  },
  {
    data: {
      id: "798745",
      name: "Friends Restaurant",
      cloudinaryImageId: "b14cd9fc40129fcfb97aa7e621719d07",
      locality: "Gayatri Nagar",
      areaName: "Jairaj Nagar",
      costForTwo: "₹150 for two",
      cuisines: ["North Indian", "Chinese", "Biryani", "Tandoor", "Kebabs"],
      avgRating: 4.2,
      parentId: "84308",
    },
  },
  {
    data: {
      id: "314737",
      name: "RASOI the KITCHEN",
      cloudinaryImageId: "yjymo9nhyn7rhvafsrd3",
      locality: "Sriram Chowk",
      areaName: "Bazar Ward",
      costForTwo: "₹200 for two",
      cuisines: ["North Indian", "Maharashtrian", "Chinese", "Thalis"],
      avgRating: 3.9,
      parentId: "167341",
    },
  },
];
